name: verkko-fillet-local-test
channels:
  - r
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - alabaster=0.7.16
  - alsa-lib=1.2.11
  - amply=0.1.6
  - appdirs=1.4.4
  - argcomplete=3.5.2
  - argh=0.31.3
  - asttokens=3.0.0
  - attr=2.5.1
  - attrs=24.3.0
  - bamtools=2.5.2
  - bbmap=39.13
  - bedops=2.4.42
  - bedtools=2.31.1
  - binutils_impl_linux-64=2.43
  - bioconductor-biobase=2.62.0
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocio=1.12.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biostrings=2.70.1
  - bioconductor-bsgenome=1.70.1
  - bioconductor-data-packages=20250101
  - bioconductor-delayedarray=0.28.0
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicalignments=1.38.0
  - bioconductor-genomicranges=1.54.1
  - bioconductor-iranges=2.36.0
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-rhtslib=2.4.0
  - bioconductor-rsamtools=2.18.0
  - bioconductor-rtracklayer=1.62.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-sparsearray=1.2.2
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - biopython=1.78
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwa=0.7.18
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.4
  - ca-certificates=2025.4.26
  - cairo=1.18.0
  - capnproto=1.0.2
  - certifi=2025.1.31
  - cffi=1.17.1
  - chain2paf=0.1.1
  - charset-normalizer=3.4.0
  - click=8.1.8
  - coin-or-cbc=2.10.12
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.10
  - coin-or-utils=2.11.11
  - coincbc=2.10.12
  - colorama=0.4.6
  - comm=0.2.2
  - compleasm=0.2.7
  - configargparse=1.7
  - connection_pool=0.0.3
  - contourpy=1.3.0
  - curl=8.8.0
  - cycler=0.12.1
  - datrie=0.8.2
  - dbus=1.13.6
  - debugpy=1.8.11
  - decorator=5.1.1
  - dendropy=4.5.2
  - dill=0.3.9
  - docutils=0.21.2
  - dpath=2.2.0
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.6.4
  - findutils=4.6.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.12.1
  - fribidi=1.0.10
  - gcc_impl_linux-64=14.2.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gffutils=0.13
  - gfortran_impl_linux-64=14.2.0
  - giflib=5.2.2
  - gitdb=4.0.11
  - gitpython=3.1.43
  - glib=2.80.2
  - glib-tools=2.80.2
  - gnuplot=5.4.10
  - graphaligner=1.0.20
  - graphite2=1.3.13
  - greenlet=3.1.1
  - gsl=2.7
  - gst-plugins-base=1.24.4
  - gstreamer=1.24.4
  - gxx_impl_linux-64=14.2.0
  - h2=4.1.0
  - harfbuzz=8.5.0
  - hmmer=3.1b2
  - hpack=4.0.0
  - htslib=1.21
  - humanfriendly=10.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.5.0
  - importlib-resources=6.4.5
  - importlib_resources=6.4.5
  - interlap=0.2.7
  - ipykernel=6.29.5
  - ipython=8.18.1
  - itables=2.2.4
  - jedi=0.19.2
  - jemalloc=5.2.0
  - jinja2=3.1.4
  - joblib=1.4.2
  - jq=1.7.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter-cache=1.0.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - k8=0.2.5
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.43
  - lerc=4.0.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang13=18.1.7
  - libcups=2.3.3
  - libcurl=8.8.0
  - libdeflate=1.20
  - libdivsufsort=2.0.2
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.4
  - libffi=3.4.2
  - libflac=1.4.3
  - libgcc=14.2.0
  - libgcc-devel_linux-64=14.2.0
  - libgcc-ng=14.2.0
  - libgcrypt-lib=1.11.0
  - libgd=2.3.3
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgit2=1.8.1
  - libglib=2.80.2
  - libgomp=14.2.0
  - libgpg-error=1.51
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.7
  - liblzma=5.6.3
  - liblzma-devel=5.6.3
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libogg=1.3.5
  - libopenblas=0.3.28
  - libopenssl-static=3.5.0
  - libopus=1.3.1
  - libpng=1.6.43
  - libpq=16.6
  - libprotobuf=3.14.0
  - libsanitizer=14.2.0
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=14.2.0
  - libstdcxx-ng=14.2.0
  - libsystemd0=256.9
  - libtiff=4.6.0
  - libuuid=2.38.1
  - libuv=1.49.2
  - libvorbis=1.3.7
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libxcrypt=4.4.36
  - libxkbcommon=1.7.0
  - libxml2=2.12.7
  - libzlib=1.2.13
  - liftoff=1.6.3
  - lz4-c=1.10.0
  - make=4.4.1
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - mash=2.3
  - mashmap=3.1.3
  - matplotlib-inline=0.1.7
  - mbg=1.0.16
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - meryl=1.4.1
  - minimap2=2.24
  - miniprot=0.13
  - mpg123=1.32.9
  - multiprocess=0.70.17
  - munkres=1.1.4
  - mysql-common=8.3.0
  - mysql-connector-c=6.1.11
  - mysql-libs=8.3.0
  - myst-nb=1.2.0
  - myst-parser=3.0.1
  - natsort=8.4.0
  - nbclient=0.10.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nspr=4.36
  - nss=3.100
  - numpy=2.0.2
  - oniguruma=6.9.10
  - openblas=0.3.28
  - openjdk=22.0.1
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - pandoc=3.6.1
  - pango=1.54.0
  - parasail-python=1.3.4
  - parso=0.8.4
  - patsy=1.0.1
  - pb-cpg-tools=3.0.0
  - pcre2=10.43
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.3.1
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - plac=1.4.3
  - platformdirs=4.3.6
  - plotly=5.24.1
  - ply=3.11
  - prompt-toolkit=3.0.48
  - protobuf=3.14.0
  - psutil=6.1.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pyfaidx=0.8.1.3
  - pygments=2.18.0
  - pyparsing=3.2.0
  - pypickle=1.1.0
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pysam=0.22.1
  - pysocks=1.7.1
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2024.2
  - python_abi=3.9
  - pytz=2024.1
  - pyvcf3=1.0.3
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qt-main=5.15.8
  - r-abind=1.4_5
  - r-askpass=1.2.1
  - r-assertthat=0.2.1
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-bh=1.87.0_1
  - r-bitops=1.0_9
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-bslib=0.8.0
  - r-cachem=1.1.0
  - r-callr=3.7.6
  - r-cli=3.6.3
  - r-clipr=0.8.0
  - r-codetools=0.2_20
  - r-commonmark=1.9.2
  - r-cpp11=0.5.1
  - r-crayon=1.5.3
  - r-credentials=2.0.2
  - r-curl=6.0.1
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diffobj=0.3.5
  - r-digest=0.6.37
  - r-downlit=0.4.4
  - r-ellipsis=0.3.2
  - r-evaluate=1.0.1
  - r-fansi=1.0.6
  - r-fastmap=1.2.0
  - r-fontawesome=0.5.3
  - r-formatr=1.14
  - r-fs=1.6.5
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gert=2.1.4
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-glue=1.8.0
  - r-highr=0.11
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpuv=1.6.15
  - r-httr2=1.0.7
  - r-ini=0.3.1
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.9
  - r-knitr=1.49
  - r-lambda.r=1.2.4
  - r-later=1.4.1
  - r-lattice=0.22_6
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_60
  - r-matrix=1.6_5
  - r-matrixstats=1.4.1
  - r-memoise=2.0.1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-openssl=2.2.2
  - r-pillar=1.10.0
  - r-pkgbuild=1.4.5
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.1.1
  - r-pkgload=1.4.0
  - r-praise=1.0.0
  - r-prettyunits=1.2.0
  - r-processx=3.8.4
  - r-profvis=0.4.0
  - r-promises=1.3.2
  - r-ps=1.8.1
  - r-purrr=1.0.2
  - r-r6=2.5.1
  - r-ragg=1.3.3
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcpp=1.0.13_1
  - r-rcurl=1.98_1.16
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-restfulr=0.0.15
  - r-rjson=0.2.23
  - r-rlang=1.1.4
  - r-rmarkdown=2.29
  - r-roxygen2=7.3.2
  - r-rprojroot=2.0.4
  - r-rstudioapi=0.17.1
  - r-rversions=2.1.2
  - r-sass=0.4.9
  - r-sessioninfo=1.2.2
  - r-shiny=1.10.0
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-sys=3.4.3
  - r-systemfonts=1.1.0
  - r-testthat=3.2.1.1
  - r-textshaping=0.4.0
  - r-tibble=3.2.1
  - r-tinytex=0.54
  - r-urlchecker=1.0.1
  - r-usethis=3.1.0
  - r-utf8=1.2.4
  - r-vctrs=0.6.5
  - r-waldo=0.6.1
  - r-whisker=0.4.1
  - r-withr=3.0.2
  - r-xfun=0.49
  - r-xml=3.99_0.17
  - r-xml2=1.3.6
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.10
  - r-zip=2.3.1
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - reretry=0.11.8
  - rpds-py=0.22.3
  - samtools=1.21
  - scikit-learn=1.6.1
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - sed=4.8
  - sepp=4.4.0
  - seqkit=2.9.0
  - seqtk=1.4
  - setuptools=75.6.0
  - simplejson=3.20.1
  - sip=6.7.12
  - six=1.17.0
  - smart_open=7.1.0
  - smmap=5.0.0
  - snakemake-minimal=7.32.4
  - snowballstemmer=2.2.0
  - sphinx=7.4.7
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sqlalchemy=2.0.38
  - sqlite=3.46.0
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - stopit=1.1.2
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tenacity=9.0.0
  - threadpoolctl=3.5.0
  - throttler=1.2.2
  - tk=8.6.14
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.2
  - toposort=1.10
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - ucsc-wigtobigwig=472
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - verkko=2.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - winnowmap=2.03
  - wrapt=1.17.0
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.42
  - xmltodict=0.14.2
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.5
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-libxtst=1.2.5
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.6.3
  - xz-gpl-tools=5.6.3
  - xz-tools=5.6.3
  - yaml=0.2.5
  - yq=3.4.3
  - yte=1.5.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - adjusttext==1.3.0
      - asciitree==0.3.3
      - babel==2.16.0
      - backports-tarfile==1.2.0
      - biser==1.4
      - blosc2==2.5.1
      - build==1.2.2.post1
      - bx-python==0.13.0
      - cooler==0.10.3
      - cryptography==44.0.0
      - cytoolz==1.0.1
      - future==1.0.0
      - gfapy==1.2.3
      - h5py==3.13.0
      - hatchling==1.27.0
      - hicmatrix==17.2
      - igv-reports==1.14.1
      - iniconfig==2.0.0
      - intervaltree==3.1.0
      - jaraco-classes==3.4.0
      - jaraco-context==6.0.1
      - jaraco-functools==4.1.0
      - jeepney==0.8.0
      - kaleido==0.2.1
      - keyring==25.6.0
      - matplotlib==3.8.4
      - more-itertools==10.6.0
      - msgpack==1.1.0
      - ncls==0.0.68
      - ndindex==1.9.2
      - nh3==0.2.20
      - numexpr==2.10.2
      - pathspec==0.12.1
      - pkginfo==1.12.0
      - pluggy==1.5.0
      - py-cpuinfo==9.0.0
      - pybedtools==0.11.0
      - pybigwig==0.3.24
      - pygenometracks==3.9
      - pyproject-hooks==1.2.0
      - pytest==8.3.5
      - readme-renderer==44.0
      - requests-toolbelt==1.0.0
      - rfc3986==2.0.0
      - rich==13.9.4
      - secretstorage==3.3.3
      - session-info==1.0.0
      - sortedcontainers==2.4.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stdlib-list==0.11.0
      - tables==3.9.2
      - toolz==1.0.0
      - trove-classifiers==2025.1.15.22
      - twine==6.0.1
